name: Release Pipeline

on:
  push:
    branches:
      - main
      - production
env:
    #ENVIRONMENT: staging                                       # e.g production-11 or staging                                    # e.g username
    ECR_REPOSITORY: "lloyd"                           # e.g upsider/images/email-service
    REPO_NAME: "lloyd"
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release --no-ci
