name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust to your preferred Node.js version

      - name: Install dependencies
        run: npm install
        

      - name: Run Semantic Release
        run: npm run release

      - name: Push changes
        run: git push --follow-tags

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*  # Adjust the path to your release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
