name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
  
      - name: Run Semantic Release
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release

      - name: get-npm-version
        # if: ${{ github.event_name == 'push' }}
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: validate version
        run: |
          echo "app-version: ${{ steps.package-version.outputs.current-version}}"
          echo "TAG: ${{steps.package-version.outputs.current-version}}"  