name: Semantic Release

on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - name: Get latest pre-release tag
        id: pre-release-tag
        run: |
          pre_release_tag=$(git describe --abbrev=0 --tags --match "*-*")
          echo "::set-output name=pre_release_tag::$pre_release_tag"
        
      - name: Get latest release tag
        id: release-tag
        run: |
          release_tag=$(git describe --abbrev=0 --tags --match "[0-9]*.[0-9]*.[0-9]*")
          echo "::set-output name=release_tag::$release_tag"

      - name: Display tags
        run: |
          echo "Latest Pre-release tag: ${{ steps.pre-release-tag.outputs.pre_release_tag }}"
          echo "Latest Release tag: ${{ steps.release-tag.outputs.release_tag }}"